#!/bin/bash

# add repos and update
#echo "deb http://repository.spotify.com stable non-free" >> /etc/apt/sources.list.d/spotify.list
#echo "deb http://archive.canonical.com/ubuntu raring partner" >> /etc/apt/sources.list
#echo "deb-src http://archive.canonical.com/ubuntu raring partner" >>  /etc/apt/sources.list
apt-get update


apt-get install build-essential git git-svn git-doc git-extras git-man -y
apt-get install mercurial -y
apt-get install zsh tmux -y

apt-get install libx11-dev libxt-dev ctags zsh -y
apt-get install gdebi-core -y

# random languages

apt-get install python-dev python-setuputils ruby-dev ruby-rvm -y
apt-get install libjpeg-dev -y
apt-get install haskell-platform -y

apt-get install valgrind -y

# work related
apt-get install nginx mysql-server mysql-client rabbitmq-server -y
apt-get install skype chromium-browser -y

# LibreOffice
sudo apt-get install libreoffice libreoffice-gtk -y

# steam
apt-get install steam -y

# spotify
apt-get install spotify-client -y

# rtorrent
apt-get install vlc rtorrent -y

# build/install vim

sudo apt-get build-dep vim

cd dev
hg clone https://vim.googlecode.com/hg vim && cd vim && \
    ./configure --enable-multibyte --with-tlib=ncurses \
    --enable-pythoninterp --enable-rubyinterp --with-features=huge && \
    make -j 9 && sudo make install

cd $HOME
