#!/usr/bin/env python
from path import path
import re

cwd = path('.').abspath()

files = cwd.listdir().sort()
r_rename = re.compile(ur"(?P<num>^\d+).*$")
temp = "{orig} -> {num}{ext}"


for a_file in files:
    search = r_rename.search(a_file)
    if search:
        print temp.format(orig=a_file, ext=a_file.ext, **search.groupdict)
    else:
        print a_file.name + ' -> ' + a_file.name
    a_file.move(u"{num}{ext}".format(ext=a_file.ext, **search.groupdict))
